[Unit]
After=mnt-vendor-persist.mount
Requires=mnt-vendor-persist.mount

[Service]
ExecStartPre=+/bin/sh -c 'mkdir -p /mnt/vendor/persist/sensors/registry && chown -R fastrpc:fastrpc /mnt/vendor/persist/sensors/registry || true'